// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFdqkzs6hA8w23sYmpNKymfo-EZD0O6KQ',
    appId: '1:279274214780:android:e54b10c7e05f64df0e40f9',
    messagingSenderId: '279274214780',
    projectId: 'firstapp-262bc',
    databaseURL: 'https://firstapp-262bc-default-rtdb.firebaseio.com',
    storageBucket: 'firstapp-262bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAovGpB-ERFvraZLk3YAprIzvDOuz-7-DQ',
    appId: '1:279274214780:ios:96368b1fa394e1e10e40f9',
    messagingSenderId: '279274214780',
    projectId: 'firstapp-262bc',
    databaseURL: 'https://firstapp-262bc-default-rtdb.firebaseio.com',
    storageBucket: 'firstapp-262bc.firebasestorage.app',
    iosBundleId: 'com.example.personality',
  );
}
